wandb_version: 1

policy:
  desc: null
  value: TD3_BC
env:
  desc: null
  value: mujoco/pusher/expert-v0
seed:
  desc: null
  value: 0
batch_size:
  desc: null
  value: 256
discount:
  desc: null
  value: 0.99
tau:
  desc: null
  value: 0.005
policy_noise:
  desc: null
  value: 0.2
noise_clip:
  desc: null
  value: 0.5
policy_freq:
  desc: null
  value: 1
alpha:
  desc: null
  value: 2.5
horizon:
  desc: null
  value: 1
expl_noise:
  desc: null
  value: 0.3
start_timesteps:
  desc: null
  value: 5000.0
max_timesteps:
  desc: null
  value: 1000000.0
eval_freq:
  desc: null
  value: 5000.0
_wandb:
  desc: null
  value:
    python_version: 3.10.18
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1757080351.329436
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 15
      - 16
      - 23
      4: 3.10.18
      5: 0.15.3
      8:
      - 3
      - 5
