obs_dim: 46
action_dim: 7
cfg:
  num_epochs: 1
  batch_size: 32
  learning_rate: 0.0001
  eval_interval: 10
  checkpoint_dir: ./checkpoint_t
  dataset_name: mujoco/pusher/expert-v0
  obs_horizon: 2
  pred_horizon: 64
  action_horizon: 32
  inference_steps: 1
  window_stride: 1
  time_dim: 32
  hidden_dim: 256
  sigma: 0.0
  normalize_data: true
  test_episodes: 20
  max_steps: 300
  action_dim: 7
  mixed_precision: 32-true
  gradient_accumulation_steps: 1
  num_workers: 0
  grad_clip_value: 1.0
  cql_alpha: 1.0
  cql_temp: 1.0
  cql_num_samples: 10
  tau: 0.005
  gamma: 0.99
  actor_update_freq: 1
  target_update_freq: 1
  normalize_q_loss: true
  device: cuda
