wandb_version: 1

policy:
  desc: null
  value: TD3
env:
  desc: null
  value: Pendulum-v1
seed:
  desc: null
  value: 0
start_timesteps:
  desc: null
  value: 25000.0
eval_freq:
  desc: null
  value: 500
max_timesteps:
  desc: null
  value: 1000
expl_noise:
  desc: null
  value: 0.1
batch_size:
  desc: null
  value: 256
discount:
  desc: null
  value: 0.99
tau:
  desc: null
  value: 0.005
policy_noise:
  desc: null
  value: 0.2
noise_clip:
  desc: null
  value: 0.5
policy_freq:
  desc: null
  value: 2
action_chunk_size:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    python_version: 3.10.18
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1757083956.721612
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.18
      5: 0.15.3
      8:
      - 3
      - 5
