# MyReinFlow 配置文件
# 这个文件包含了不同训练任务的默认配置

# 行为克隆配置
behavioral_cloning:
  dataset_name: "mujoco/pusher/expert-v0"
  num_epochs: 50
  batch_size: 256
  learning_rate: 0.0003
  eval_freq: 5
  eval_episodes: 5
  seed: 42
  project_name: "behavioral-cloning"
  experiment_name: "bc-minari"
  render_mode: "human"  # 'none' | 'human' | 'rgb_array'
  record_video: false
  video_dir: "videos"
  save_model_path: null

# FQL配置
fql:
  dataset_name: "mujoco/pusher/expert-v0"
  cond_steps: 1
  horizon_steps: 4
  batch_size: 256
  num_epochs: 20
  lr_flow: 0.0003
  lr_actor: 0.0003
  lr_critic: 0.0003
  weight_decay: 0.0
  max_grad_norm: 1.0
  gamma: 0.99
  tau: 0.005
  alpha_distill: 1.0
  normalize_q_loss: false
  inference_steps: 32
  seed: 42
  target_q_agg: "min"  # 'min' | 'mean'
  hidden_dim_actor: 512
  mlp_dims_critic: [256, 256]
  mlp_dims_flow: [256, 256]
  residual_mlp: false
  time_dim: 16
  num_workers: 0
  use_amp: true
  project_name: "fql-baseline"
  experiment_name: "fql-minari"
  eval_episodes: 5
  eval_freq: 5
  render_mode: "human"
  record_video: false
  video_dir: "videos"
  save_model_path: null
  only_optimize_bc_flow: false

# 2D Mean Flow示例配置  
mean_flow_2d:
  epochs: 10000
  batch_size: 512
  lr: 0.001
  device: "auto"  # 'auto' | 'cpu' | 'cuda'
