wandb_version: 1

dataset_name:
  desc: null
  value: mujoco/pusher/expert-v0
cond_steps:
  desc: null
  value: 1
horizon_steps:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 256
num_epochs:
  desc: null
  value: 20
lr_flow:
  desc: null
  value: 0.0003
lr_actor:
  desc: null
  value: 0.0003
lr_critic:
  desc: null
  value: 0.0003
weight_decay:
  desc: null
  value: 0.0
max_grad_norm:
  desc: null
  value: 1.0
gamma:
  desc: null
  value: 0.99
tau:
  desc: null
  value: 0.005
alpha_distill:
  desc: null
  value: 1.0
normalize_q_loss:
  desc: null
  value: false
inference_steps:
  desc: null
  value: 32
seed:
  desc: null
  value: 42
hidden_dim_actor:
  desc: null
  value: 512
mlp_dims_critic:
  desc: null
  value:
  - 256
  - 256
mlp_dims_flow:
  desc: null
  value:
  - 256
  - 256
residual_mlp:
  desc: null
  value: false
time_dim:
  desc: null
  value: 16
num_workers:
  desc: null
  value: 0
use_amp:
  desc: null
  value: true
project_name:
  desc: null
  value: fql-baseline
experiment_name:
  desc: null
  value: fql-minari
eval_episodes:
  desc: null
  value: 5
eval_freq:
  desc: null
  value: 5
render_mode:
  desc: null
  value: none
record_video:
  desc: null
  value: false
video_dir:
  desc: null
  value: videos
save_model_path:
  desc: null
  value: null
only_optimize_bc_flow:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.10.18
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1755090678.592204
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.18
      5: 0.15.3
      8:
      - 3
      - 5
